-- ============================================================
--  GEOGRAPHIC MASTERS - World Countries Seed Script
--  Platform : SQL Server (T-SQL - Full Unicode Support)
--  Description:
--    Inserts world countries into CountryMasters table.
--    Uses N'...' T-SQL Unicode literals to preserve special currency symbols.
--    Safe & Idempotent (uses MERGE to prevent duplicate records).
-- ============================================================

USE SchoolErpDB;
GO

PRINT 'Seeding World Countries into CountryMasters...';
GO

MERGE INTO CountryMasters AS Target
USING (VALUES
    (N'Afghanistan',                          N'AF', N'+93',   N'AFN', N'؋'),
    (N'Albania',                              N'AL', N'+355',  N'ALL', N'L'),
    (N'Algeria',                              N'DZ', N'+213',  N'DZD', N'د.ج'),
    (N'Andorra',                              N'AD', N'+376',  N'EUR', N'€'),
    (N'Angola',                               N'AO', N'+244',  N'AOA', N'Kz'),
    (N'Antigua and Barbuda',                  N'AG', N'+1-268',N'XCD', N'$'),
    (N'Argentina',                            N'AR', N'+54',   N'ARS', N'$'),
    (N'Armenia',                              N'AM', N'+374',  N'AMD', N'֏'),
    (N'Australia',                            N'AU', N'+61',   N'AUD', N'$'),
    (N'Austria',                              N'AT', N'+43',   N'EUR', N'€'),
    (N'Azerbaijan',                           N'AZ', N'+994',  N'AZN', N'₼'),
    (N'Bahamas',                              N'BS', N'+1-242',N'BSD', N'$'),
    (N'Bahrain',                              N'BH', N'+973',  N'BHD', N'د.ب'),
    (N'Bangladesh',                           N'BD', N'+880',  N'BDT', N'৳'),
    (N'Barbados',                             N'BB', N'+1-246',N'BBD', N'$'),
    (N'Belarus',                              N'BY', N'+375',  N'BYN', N'Br'),
    (N'Belgium',                              N'BE', N'+32',   N'EUR', N'€'),
    (N'Belize',                               N'BZ', N'+501',  N'BZD', N'$'),
    (N'Benin',                                N'BJ', N'+229',  N'XOF', N'CFA'),
    (N'Bhutan',                               N'BT', N'+975',  N'BTN', N'Nu.'),
    (N'Bolivia',                              N'BO', N'+591',  N'BOB', N'Bs.'),
    (N'Bosnia and Herzegovina',               N'BA', N'+387',  N'BAM', N'KM'),
    (N'Botswana',                             N'BW', N'+267',  N'BWP', N'P'),
    (N'Brazil',                               N'BR', N'+55',   N'BRL', N'R$'),
    (N'Brunei',                               N'BN', N'+673',  N'BND', N'$'),
    (N'Bulgaria',                             N'BG', N'+359',  N'BGN', N'лв'),
    (N'Burkina Faso',                         N'BF', N'+226',  N'XOF', N'CFA'),
    (N'Burundi',                              N'BI', N'+257',  N'BIF', N'FBu'),
    (N'Cambodia',                             N'KH', N'+855',  N'KHR', N'៛'),
    (N'Cameroon',                             N'CM', N'+237',  N'XAF', N'FCFA'),
    (N'Canada',                               N'CA', N'+1',    N'CAD', N'$'),
    (N'Cape Verde',                           N'CV', N'+238',  N'CVE', N'Esc'),
    (N'Central African Republic',             N'CF', N'+236',  N'XAF', N'FCFA'),
    (N'Chad',                                 N'TD', N'+235',  N'XAF', N'FCFA'),
    (N'Chile',                                N'CL', N'+56',   N'CLP', N'$'),
    (N'China',                                N'CN', N'+86',   N'CNY', N'¥'),
    (N'Colombia',                             N'CO', N'+57',   N'COP', N'$'),
    (N'Comoros',                              N'KM', N'+269',  N'KMF', N'CF'),
    (N'Congo',                                N'CG', N'+242',  N'XAF', N'FCFA'),
    (N'Costa Rica',                           N'CR', N'+506',  N'CRC', N'₡'),
    (N'Croatia',                              N'HR', N'+385',  N'EUR', N'€'),
    (N'Cuba',                                 N'CU', N'+53',   N'CUP', N'$'),
    (N'Cyprus',                               N'CY', N'+357',  N'EUR', N'€'),
    (N'Czech Republic',                       N'CZ', N'+420',  N'CZK', N'Kč'),
    (N'Denmark',                              N'DK', N'+45',   N'DKK', N'kr'),
    (N'Djibouti',                             N'DJ', N'+253',  N'DJF', N'Fdj'),
    (N'Dominica',                             N'DM', N'+1-767',N'XCD', N'$'),
    (N'Dominican Republic',                   N'DO', N'+1-809',N'DOP', N'RD$'),
    (N'Ecuador',                              N'EC', N'+593',  N'USD', N'$'),
    (N'Egypt',                                N'EG', N'+20',   N'EGP', N'E£'),
    (N'El Salvador',                          N'SV', N'+503',  N'USD', N'$'),
    (N'Equatorial Guinea',                    N'GQ', N'+240',  N'XAF', N'FCFA'),
    (N'Eritrea',                              N'ER', N'+291',  N'ERN', N'Nfk'),
    (N'Estonia',                              N'EE', N'+372',  N'EUR', N'€'),
    (N'Eswatini',                             N'SZ', N'+268',  N'SZL', N'E'),
    (N'Ethiopia',                             N'ET', N'+251',  N'ETB', N'Br'),
    (N'Fiji',                                 N'FJ', N'+679',  N'FJD', N'$'),
    (N'Finland',                              N'FI', N'+358',  N'EUR', N'€'),
    (N'France',                               N'FR', N'+33',   N'EUR', N'€'),
    (N'Gabon',                                N'GA', N'+241',  N'XAF', N'FCFA'),
    (N'Gambia',                               N'GM', N'+220',  N'GMD', N'D'),
    (N'Georgia',                              N'GE', N'+995',  N'GEL', N'₾'),
    (N'Germany',                              N'DE', N'+49',   N'EUR', N'€'),
    (N'Ghana',                                N'GH', N'+233',  N'GHS', N'GH₵'),
    (N'Greece',                               N'GR', N'+30',   N'EUR', N'€'),
    (N'Grenada',                              N'GD', N'+1-473',N'XCD', N'$'),
    (N'Guatemala',                            N'GT', N'+502',  N'GTQ', N'Q'),
    (N'Guinea',                               N'GN', N'+224',  N'GNF', N'FG'),
    (N'Guinea-Bissau',                        N'GW', N'+245',  N'XOF', N'CFA'),
    (N'Guyana',                               N'GY', N'+592',  N'GYD', N'$'),
    (N'Haiti',                                N'HT', N'+509',  N'HTG', N'G'),
    (N'Honduras',                             N'HN', N'+504',  N'HNL', N'L'),
    (N'Hungary',                              N'HU', N'+36',   N'HUF', N'Ft'),
    (N'Iceland',                              N'IS', N'+354',  N'ISK', N'kr'),
    (N'India',                                N'IN', N'+91',   N'INR', N'₹'),
    (N'Indonesia',                            N'ID', N'+62',   N'IDR', N'Rp'),
    (N'Iran',                                 N'IR', N'+98',   N'IRR', N'﷼'),
    (N'Iraq',                                 N'IQ', N'+964',  N'IQD', N'ع.د'),
    (N'Ireland',                              N'IE', N'+353',  N'EUR', N'€'),
    (N'Israel',                               N'IL', N'+972',  N'ILS', N'₪'),
    (N'Italy',                                N'IT', N'+39',   N'EUR', N'€'),
    (N'Jamaica',                              N'JM', N'+1-876',N'JMD', N'J$'),
    (N'Japan',                                N'JP', N'+81',   N'JPY', N'¥'),
    (N'Jordan',                               N'JO', N'+962',  N'JOD', N'د.ا'),
    (N'Kazakhstan',                           N'KZ', N'+7',    N'KZT', N'₸'),
    (N'Kenya',                                N'KE', N'+254',  N'KES', N'KSh'),
    (N'Kiribati',                             N'KI', N'+686',  N'AUD', N'$'),
    (N'Kuwait',                               N'KW', N'+965',  N'KWD', N'د.ك'),
    (N'Kyrgyzstan',                           N'KG', N'+996',  N'KGS', N'сом'),
    (N'Laos',                                 N'LA', N'+856',  N'LAK', N'₭'),
    (N'Latvia',                               N'LV', N'+371',  N'EUR', N'€'),
    (N'Lebanon',                              N'LB', N'+961',  N'LBP', N'ل.ل'),
    (N'Lesotho',                              N'LS', N'+266',  N'LSL', N'L'),
    (N'Liberia',                              N'LR', N'+231',  N'LRD', N'$'),
    (N'Libya',                                N'LY', N'+218',  N'LYD', N'ل.د'),
    (N'Liechtenstein',                        N'LI', N'+423',  N'CHF', N'CHF'),
    (N'Lithuania',                            N'LT', N'+370',  N'EUR', N'€'),
    (N'Luxembourg',                           N'LU', N'+352',  N'EUR', N'€'),
    (N'Madagascar',                           N'MG', N'+261',  N'MGA', N'Ar'),
    (N'Malawi',                               N'MW', N'+265',  N'MWK', N'MK'),
    (N'Malaysia',                             N'MY', N'+60',   N'MYR', N'RM'),
    (N'Maldives',                             N'MV', N'+960',  N'MVR', N'Rf'),
    (N'Mali',                                 N'ML', N'+223',  N'XOF', N'CFA'),
    (N'Malta',                                N'MT', N'+356',  N'EUR', N'€'),
    (N'Marshall Islands',                     N'MH', N'+692',  N'USD', N'$'),
    (N'Mauritania',                           N'MR', N'+222',  N'MRU', N'UM'),
    (N'Mauritius',                            N'MU', N'+230',  N'MUR', N'₨'),
    (N'Mexico',                               N'MX', N'+52',   N'MXN', N'$'),
    (N'Micronesia',                           N'FM', N'+691',  N'USD', N'$'),
    (N'Moldova',                              N'MD', N'+373',  N'MDL', N'L'),
    (N'Monaco',                               N'MC', N'+377',  N'EUR', N'€'),
    (N'Mongolia',                             N'MN', N'+976',  N'MNT', N'₮'),
    (N'Montenegro',                           N'ME', N'+382',  N'EUR', N'€'),
    (N'Morocco',                              N'MA', N'+212',  N'MAD', N'د.م.'),
    (N'Mozambique',                           N'MZ', N'+258',  N'MZN', N'MT'),
    (N'Myanmar',                              N'MM', N'+95',   N'MMK', N'Ks'),
    (N'Namibia',                              N'NA', N'+264',  N'NAD', N'$'),
    (N'Nauru',                                N'NR', N'+674',  N'AUD', N'$'),
    (N'Nepal',                                N'NP', N'+977',  N'NPR', N'रू'),
    (N'Netherlands',                          N'NL', N'+31',   N'EUR', N'€'),
    (N'New Zealand',                          N'NZ', N'+64',   N'NZD', N'$'),
    (N'Nicaragua',                            N'NI', N'+505',  N'NIO', N'C$'),
    (N'Niger',                                N'NE', N'+227',  N'XOF', N'CFA'),
    (N'Nigeria',                              N'NG', N'+234',  N'NGN', N'₦'),
    (N'North Korea',                          N'KP', N'+850',  N'KPW', N'₩'),
    (N'North Macedonia',                      N'MK', N'+389',  N'MKD', N'ден'),
    (N'Norway',                               N'NO', N'+47',   N'NOK', N'kr'),
    (N'Oman',                                 N'OM', N'+968',  N'OMR', N'ر.ع.'),
    (N'Pakistan',                             N'PK', N'+92',   N'PKR', N'Rs'),
    (N'Palau',                                N'PW', N'+680',  N'USD', N'$'),
    (N'Palestine',                            N'PS', N'+970',  N'ILS', N'₪'),
    (N'Panama',                               N'PA', N'+507',  N'PAB', N'B/.'),
    (N'Papua New Guinea',                     N'PG', N'+675',  N'PGK', N'K'),
    (N'Paraguay',                             N'PY', N'+595',  N'PYG', N'₲'),
    (N'Peru',                                 N'PE', N'+51',   N'PEN', N'S/'),
    (N'Philippines',                          N'PH', N'+63',   N'PHP', N'₱'),
    (N'Poland',                               N'PL', N'+48',   N'PLN', N'zł'),
    (N'Portugal',                             N'PT', N'+351',  N'EUR', N'€'),
    (N'Qatar',                                N'QA', N'+974',  N'QAR', N'ر.ق'),
    (N'Romania',                              N'RO', N'+40',   N'RON', N'lei'),
    (N'Russia',                               N'RU', N'+7',    N'RUB', N'₽'),
    (N'Rwanda',                               N'RW', N'+250',  N'RWF', N'FRw'),
    (N'Saint Kitts and Nevis',                N'KN', N'+1-869',N'XCD', N'$'),
    (N'Saint Lucia',                          N'LC', N'+1-758',N'XCD', N'$'),
    (N'Saint Vincent and the Grenadines',     N'VC', N'+1-784',N'XCD', N'$'),
    (N'Samoa',                                N'WS', N'+685',  N'WST', N'WS$'),
    (N'San Marino',                           N'SM', N'+378',  N'EUR', N'€'),
    (N'Sao Tome and Principe',                N'ST', N'+239',  N'STN', N'Db'),
    (N'Saudi Arabia',                         N'SA', N'+966',  N'SAR', N'ر.س'),
    (N'Senegal',                              N'SN', N'+221',  N'XOF', N'CFA'),
    (N'Serbia',                               N'RS', N'+381',  N'RSD', N'дин.'),
    (N'Seychelles',                           N'SC', N'+248',  N'SCR', N'₨'),
    (N'Sierra Leone',                         N'SL', N'+232',  N'SLE', N'Le'),
    (N'Singapore',                            N'SG', N'+65',   N'SGD', N'$'),
    (N'Slovakia',                             N'SK', N'+421',  N'EUR', N'€'),
    (N'Slovenia',                             N'SI', N'+386',  N'EUR', N'€'),
    (N'Solomon Islands',                      N'SB', N'+677',  N'SBD', N'$'),
    (N'Somalia',                              N'SO', N'+252',  N'SOS', N'Sh.So.'),
    (N'South Africa',                         N'ZA', N'+27',   N'ZAR', N'R'),
    (N'South Korea',                          N'KR', N'+82',   N'KRW', N'₩'),
    (N'South Sudan',                          N'SS', N'+211',  N'SSP', N'£'),
    (N'Spain',                                N'ES', N'+34',   N'EUR', N'€'),
    (N'Sri Lanka',                            N'LK', N'+94',   N'LKR', N'Rs'),
    (N'Sudan',                                N'SD', N'+249',  N'SDG', N'ج.س.'),
    (N'Suriname',                             N'SR', N'+597',  N'SRD', N'$'),
    (N'Sweden',                               N'SE', N'+46',   N'SEK', N'kr'),
    (N'Switzerland',                          N'CH', N'+41',   N'CHF', N'CHF'),
    (N'Syria',                                N'SY', N'+963',  N'SYP', N'LS'),
    (N'Taiwan',                               N'TW', N'+886',  N'TWD', N'NT$'),
    (N'Tajikistan',                           N'TJ', N'+992',  N'TJS', N'SM'),
    (N'Tanzania',                             N'TZ', N'+255',  N'TZS', N'TSh'),
    (N'Thailand',                             N'TH', N'+66',   N'THB', N'฿'),
    (N'Timor-Leste',                          N'TL', N'+670',  N'USD', N'$'),
    (N'Togo',                                 N'TG', N'+228',  N'XOF', N'CFA'),
    (N'Tonga',                                N'TO', N'+676',  N'TOP', N'T$'),
    (N'Trinidad and Tobago',                  N'TT', N'+1-868',N'TTD', N'TT$'),
    (N'Tunisia',                              N'TN', N'+216',  N'TND', N'د.ت'),
    (N'Turkey',                               N'TR', N'+90',   N'TRY', N'₺'),
    (N'Turkmenistan',                         N'TM', N'+993',  N'TMT', N'TMT'),
    (N'Tuvalu',                               N'TV', N'+688',  N'AUD', N'$'),
    (N'Uganda',                               N'UG', N'+256',  N'UGX', N'USh'),
    (N'Ukraine',                              N'UA', N'+380',  N'UAH', N'₴'),
    (N'United Arab Emirates',                 N'AE', N'+971',  N'AED', N'د.إ'),
    (N'United Kingdom',                       N'GB', N'+44',   N'GBP', N'£'),
    (N'United States',                        N'US', N'+1',    N'USD', N'$'),
    (N'Uruguay',                              N'UY', N'+598',  N'UYU', N'$U'),
    (N'Uzbekistan',                           N'UZ', N'+998',  N'UZS', N'soʻm'),
    (N'Vanuatu',                              N'VU', N'+678',  N'VUV', N'VT'),
    (N'Vatican City',                         N'VA', N'+379',  N'EUR', N'€'),
    (N'Venezuela',                            N'VE', N'+58',   N'VES', N'Bs.S'),
    (N'Vietnam',                              N'VN', N'+84',   N'VND', N'₫'),
    (N'Yemen',                                N'YE', N'+967',  N'YER', N'﷼'),
    (N'Zambia',                               N'ZM', N'+260',  N'ZMW', N'ZK'),
    (N'Zimbabwe',                             N'ZW', N'+263',  N'ZWG', N'ZiG')
) AS Source (CountryName, ISO2, PhoneCode, CurrencyCode, CurrencySymbol)
ON Target.CountryName = Source.CountryName
WHEN MATCHED THEN
    UPDATE SET 
        Target.ISO2 = Source.ISO2,
        Target.PhoneCode = Source.PhoneCode,
        Target.CurrencyCode = Source.CurrencyCode,
        Target.CurrencySymbol = Source.CurrencySymbol,
        Target.UpdatedAt = GETUTCDATE()
WHEN NOT MATCHED THEN
    INSERT (CountryName, ISO2, PhoneCode, CurrencyCode, CurrencySymbol, IsActive, CreatedAt, UpdatedAt)
    VALUES (Source.CountryName, Source.ISO2, Source.PhoneCode, Source.CurrencyCode, Source.CurrencySymbol, 1, GETUTCDATE(), GETUTCDATE());
GO

PRINT 'World Countries Seed completed successfully with full Unicode character support.';
GO
